In [2]:
import torch
print(torch.__version__)

2.8.0+cu126


In [3]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"using {torch.cuda.get_device_name(0)}")
else:
  print("GPU not available using CPU")

GPU is available
using Tesla T4


## Creating a Tensor

In [4]:
#1 using empty

a = torch.empty(2,3) # create a 2,3 shape tensor 2D ,
#empty fn allocates memeory and does not assign any value and it shows the value which are already present

print(a)

type(a) # check type

tensor([[2.1161e-32, 4.3859e-41, 2.1161e-32],
        [4.3859e-41, 0.0000e+00, 0.0000e+00]])


torch.Tensor

In [5]:
#2 using zeros

torch.zeros(2,3) # all values will be 0

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
#3 using ones

torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
#4 using rand

torch.rand(3,3) # random value between 0-1

# at each run these values will change

tensor([[0.1720, 0.7167, 0.8840],
        [0.5486, 0.6553, 0.1863],
        [0.0080, 0.6783, 0.3168]])

In [8]:
# use rand but each run value same - use seed

torch.manual_seed(100) #define seed

torch.rand(3,3)


tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539],
        [0.2627, 0.0428, 0.2080]])

In [9]:
#5 using tensor

torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [10]:
# other ways

# arange
print("using arange ->", torch.arange(0,10,2)) # range, step

# using linspace
print("using linspace ->", torch.linspace(0,10,10)) #linearly spaced, range, no. of values u need

# using eye
print("using eye ->", torch.eye(5)) # identity matrix

# using full
print("using full ->", torch.full((3, 3), 5)) # shape , item(value)

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Tensor Shapes


In [11]:
a = torch.tensor([[1,2,3],[4,5,6]])
a.shape

torch.Size([2, 3])

In [12]:
torch.empty_like(a) # make empty tensor like a tensor a (same size as 'a')

tensor([[493921239150, 489626271855, 390842023976],
        [210453397595, 214748364844, 219043332140]])

In [13]:
torch.zeros_like(a) # make zeros tensor of same size as of tensor-'a'

tensor([[0, 0, 0],
        [0, 0, 0]])

In [14]:
torch.ones_like(a)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [15]:
torch.rand_like(a) # gives error : coz "a" has intezers and rand generates float, (we have to tell explicitly to generate float)

NotImplementedError: "check_uniform_bounds" not implemented for 'Long'

In [16]:
torch.rand_like(a,dtype=torch.float32) # it works when we tell it what data type of rand

tensor([[0.1180, 0.1217, 0.7356],
        [0.7118, 0.7876, 0.4183]])

## Data Types

In [17]:
#find the data type
a = torch.tensor([[1,2,3],[4,5,6]])
a.dtype

torch.int64

In [18]:
#assign the data type

torch.tensor([1.0,2.0,3.0], dtype=torch.int32) # specify the data type

tensor([1, 2, 3], dtype=torch.int32)

In [19]:
torch.tensor([1,2,3], dtype=torch.float32)


tensor([1., 2., 3.])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


## Mathematical Operation

### 1. Scalar operation

In [20]:
x = torch.rand(3,3)
x

tensor([[0.9014, 0.9969, 0.7565],
        [0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])

In [21]:
#addition
print(x+2)

# substraction
print(x-2)

#multiplication
print(x*5)

#division
print(x/2)

#int division
print((x*100) // 3)

#mod
print(((x*100) // 3)%2)

#power
print(x**2)

tensor([[2.9014, 2.9969, 2.7565],
        [2.2239, 2.3023, 2.1784],
        [2.8238, 2.5557, 2.9770]])
tensor([[-1.0986, -1.0031, -1.2435],
        [-1.7761, -1.6977, -1.8216],
        [-1.1762, -1.4443, -1.0230]])
tensor([[4.5071, 4.9844, 3.7826],
        [1.1195, 1.5117, 0.8921],
        [4.1192, 2.7787, 4.8851]])
tensor([[0.4507, 0.4984, 0.3783],
        [0.1119, 0.1512, 0.0892],
        [0.4119, 0.2779, 0.4885]])
tensor([[30., 33., 25.],
        [ 7., 10.,  5.],
        [27., 18., 32.]])
tensor([[0., 1., 1.],
        [1., 0., 1.],
        [1., 0., 0.]])
tensor([[0.8125, 0.9938, 0.5723],
        [0.0501, 0.0914, 0.0318],
        [0.6787, 0.3089, 0.9546]])


### 2. Element wise operation

In [22]:
a  = torch.rand(2,2)
b  = torch.rand(2,2)

print(a)
print(b)

tensor([[0.4440, 0.9478],
        [0.7445, 0.4892]])
tensor([[0.2426, 0.7003],
        [0.5277, 0.2472]])


In [23]:
#addition
a+b

# substraction
a-b

# multiply
a*b

# division
a/b

#power
a**b

#mod
a % b

tensor([[0.2015, 0.2475],
        [0.2168, 0.2420]])

### 3. operation on single tensor

In [24]:

c = torch.tensor([1,-2,3,-4])

#abs(absolute value)
torch.abs(c)


# negative of tensor
torch.neg(c)

tensor([-1,  2, -3,  4])

In [25]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [26]:
#round
torch.round(d)

#ceil
torch.ceil(d) # goes to upper integer

#floor
torch.floor(d)


tensor([1., 2., 3., 4.])

In [27]:
#clamp - can keep a number in a range
torch.clamp(d, min=2, max=3)


tensor([2.0000, 2.3000, 3.0000, 3.0000])

### 4. Reduction Operation

In [28]:
e = torch.randint(size = (2,3), low =0, high = 10 )
e

tensor([[0, 9, 5],
        [7, 3, 9]])

In [31]:
#sum
torch.sum(e) #sum of matrix

# sum along columns
torch.sum(e, dim=0)

#sum along rows
torch.sum(e, dim=1)

tensor([14, 19])

In [33]:
e = torch.randint(size = (2,3), low =0, high = 10, dtype=torch.float32)
e

tensor([[4., 0., 5.],
        [7., 5., 9.]])

In [35]:
#mean
torch.mean(e)

# mean along column
torch.mean(e, dim=0)

tensor([5.5000, 2.5000, 7.0000])

In [36]:
#median
torch.median(e)

tensor(5.)

In [37]:
#max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [38]:
#product
torch.prod(e)

tensor(0.)

In [39]:
# standard deviation
torch.std(e)

tensor(3.0332)

In [40]:
#variance
torch.var(e)

tensor(9.2000)

In [41]:
#argmax
torch.argmax(e) # tells postion of largest item

tensor(5)

In [42]:
#argmin
torch.argmin(e) # tell position of smallest item

tensor(1)

### 5. Matrix Operation

In [43]:
f = torch.randint(size=(2,3), low = 0, high = 10)
g = torch.randint(size=(3,2), low = 0, high = 10)

print(f)
print(g)

tensor([[9, 7, 5],
        [9, 8, 9]])
tensor([[7, 9],
        [2, 6],
        [7, 7]])


In [44]:
#matrix multiplcation
torch.matmul(f,g)

tensor([[112, 158],
        [142, 192]])

In [46]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])

#dot product
torch.dot(vector1, vector2)

tensor(11)

###

In [47]:
# transpose
print(f)
torch.transpose(f, 0, 1 ) # matrix, which dimension to swap (swap 0 with 1)

tensor([[9, 7, 5],
        [9, 8, 9]])


tensor([[9, 9],
        [7, 8],
        [5, 9]])

In [48]:
h = torch.randint(size = (3,3), low = 0, high = 10, dtype=torch.float32)
h

tensor([[8., 3., 6.],
        [1., 5., 5.],
        [0., 4., 3.]])

In [49]:
# determinant
torch.det(h)

tensor(-25.0000)

In [50]:
# inverse
torch.inverse(h)

tensor([[ 0.2000, -0.6000,  0.6000],
        [ 0.1200, -0.9600,  1.3600],
        [-0.1600,  1.2800, -1.4800]])

### 6. Comparision Operation

In [3]:
i = torch.randint(size= (2,3), low = 0, high=10)
j = torch.randint(size= (2,3), low = 0, high=10)

print(i)
print(j)

tensor([[5, 2, 8],
        [0, 9, 5]])
tensor([[7, 0, 0],
        [2, 3, 4]])


In [9]:
# greater then
i > j

# less then
i < j

# equal to
i == j

# not equal to
i != j

# greater then equal to
i >= j

#less then equal to
i <= j

tensor([[ True, False, False],
        [ True, False, False]])

### 7. Special functions

In [10]:
k = torch.randint(size=(2,3), low = 0, high = 10)
k

tensor([[1, 6, 0],
        [7, 4, 3]])

In [11]:
#log
torch.log(k)


tensor([[0.0000, 1.7918,   -inf],
        [1.9459, 1.3863, 1.0986]])

In [12]:
#exponent
torch.exp(k)


tensor([[2.7183e+00, 4.0343e+02, 1.0000e+00],
        [1.0966e+03, 5.4598e+01, 2.0086e+01]])

In [13]:
#sqrt
torch.sqrt(k)

tensor([[1.0000, 2.4495, 0.0000],
        [2.6458, 2.0000, 1.7321]])

In [14]:
#sigmoid
torch.sigmoid(k)

tensor([[0.7311, 0.9975, 0.5000],
        [0.9991, 0.9820, 0.9526]])

In [16]:
k = torch.randint(size=(2,3), low = 0, high = 10, dtype=torch.float32)
k

tensor([[1., 5., 3.],
        [7., 8., 7.]])

In [17]:
#softmax
torch.softmax(k, dim = 0) # across which dimension to apply softmax

tensor([[0.0025, 0.0474, 0.0180],
        [0.9975, 0.9526, 0.9820]])

In [18]:
#relu
torch.relu(k)

tensor([[1., 5., 3.],
        [7., 8., 7.]])

## Inplace Operation

In [19]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.6901, 0.8362, 0.2970],
        [0.6409, 0.2825, 0.8601]])
tensor([[0.1622, 0.7825, 0.3210],
        [0.4073, 0.2430, 0.1671]])


In [20]:
m + n # element wise operation is performed and result is stored in new tensor in memory ( it will occoupy some memory),
#imagin performing this operation of large tensors it will take hell lot of storage so, we want to store it in inplace

tensor([[0.8523, 1.6186, 0.6181],
        [1.0481, 0.5255, 1.0272]])

In [22]:
m.add_(n) # m = m + n  #result stored in m tensor

tensor([[0.8523, 1.6186, 0.6181],
        [1.0481, 0.5255, 1.0272]])

In [23]:
m

tensor([[0.8523, 1.6186, 0.6181],
        [1.0481, 0.5255, 1.0272]])

In [ ]:
# what if relu

m.relu_() # rather then taking new memory and making new tensor it stores it in m only

## Copying a Tensor

In [24]:
a = torch.rand(2,3)
a

tensor([[0.4898, 0.8588, 0.9727],
        [0.5009, 0.0278, 0.9850]])

In [25]:
b = a # copy BUT problem is if a is changed then b is also changed (original changed then copy is also changed)

In [26]:
a[0][0]=0

In [27]:
a

tensor([[0.0000, 0.8588, 0.9727],
        [0.5009, 0.0278, 0.9850]])

In [28]:
b

tensor([[0.0000, 0.8588, 0.9727],
        [0.5009, 0.0278, 0.9850]])

In [29]:
# this is because both a and b points to same existing reference ( not creating new memeory)
id(a)


138315965130672

In [30]:
id(b) # both point to same memory location

138315965130672

In [31]:
#  to copy

#use clone function

b = a.clone()

In [32]:
a[0][0] = 10

In [33]:
a

tensor([[10.0000,  0.8588,  0.9727],
        [ 0.5009,  0.0278,  0.9850]])

In [34]:
b

tensor([[0.0000, 0.8588, 0.9727],
        [0.5009, 0.0278, 0.9850]])

In [35]:
# id of both a and b will be different now

print(id(a))
print(id(b))

138315965130672
138315965067936


## Tensor Operations on GPU

In [36]:
torch.cuda.is_available()

True

In [37]:
device = torch.device("cuda")

In [38]:
# creating new tensor on GPU

torch.rand((2,3), device= device)

tensor([[0.3621, 0.0048, 0.2089],
        [0.2288, 0.4986, 0.6483]], device='cuda:0')

In [40]:
# moving existing tensor to GPU

a = torch.rand(2,3) # making tensor on CPU
print(a)

b = a.to(device) # converting the CPU tensor a to GPU tensor b
print(b)

tensor([[0.7671, 0.6592, 0.1726],
        [0.4915, 0.3140, 0.8593]])
tensor([[0.7671, 0.6592, 0.1726],
        [0.4915, 0.3140, 0.8593]], device='cuda:0')


In [ ]:
# we do this because GPU saves lots of time

## Reshaping the Tensor

In [41]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [42]:
# reshape - (original shape product must be equal to reshape shape product ) 16 = 16

a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [43]:
# flatten - bring in single dimension
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [44]:
# permute

b = torch.rand(2,3,4)
print(b) # make new tensor


b.permute(2,1,0) # these are the index position of above tensor, whose position will be changed, hence shape will be changed

tensor([[[0.3229, 0.1815, 0.6522, 0.2904],
         [0.2066, 0.2561, 0.8129, 0.8197],
         [0.1736, 0.9722, 0.3391, 0.4421]],

        [[0.0504, 0.5642, 0.6068, 0.5053],
         [0.3883, 0.5024, 0.7224, 0.7581],
         [0.5290, 0.3215, 0.2340, 0.5654]]])


tensor([[[0.3229, 0.0504],
         [0.2066, 0.3883],
         [0.1736, 0.5290]],

        [[0.1815, 0.5642],
         [0.2561, 0.5024],
         [0.9722, 0.3215]],

        [[0.6522, 0.6068],
         [0.8129, 0.7224],
         [0.3391, 0.2340]],

        [[0.2904, 0.5053],
         [0.8197, 0.7581],
         [0.4421, 0.5654]]])

In [45]:
# unsqueeze

c = torch.rand(226, 226, 3)
print(c)

c.unsqueeze(0).shape # this adds new dimention at 0 index place

tensor([[[0.5240, 0.0120, 0.3958],
         [0.3973, 0.8149, 0.5749],
         [0.2796, 0.7597, 0.0641],
         ...,
         [0.8777, 0.0683, 0.4534],
         [0.3037, 0.3800, 0.1691],
         [0.6471, 0.2941, 0.4791]],

        [[0.2942, 0.3414, 0.0910],
         [0.7094, 0.8419, 0.6162],
         [0.6992, 0.1271, 0.3237],
         ...,
         [0.5003, 0.9244, 0.6420],
         [0.8189, 0.1184, 0.8125],
         [0.1651, 0.2920, 0.1563]],

        [[0.2189, 0.1516, 0.4554],
         [0.8591, 0.8997, 0.6364],
         [0.4295, 0.7348, 0.4677],
         ...,
         [0.0581, 0.3223, 0.5121],
         [0.4512, 0.9613, 0.3728],
         [0.0104, 0.0559, 0.1283]],

        ...,

        [[0.4600, 0.8791, 0.0272],
         [0.0689, 0.6000, 0.0996],
         [0.9625, 0.3352, 0.1102],
         ...,
         [0.7049, 0.7758, 0.0160],
         [0.4003, 0.6236, 0.9128],
         [0.1078, 0.9312, 0.8511]],

        [[0.8802, 0.9943, 0.9694],
         [0.1792, 0.2414, 0.4151],
         [0.

torch.Size([1, 226, 226, 3])

In [47]:
#squeeze

d = torch.rand(1,20) # 1, 20 size tensor
print(d)
d.squeeze(0) # squeez the oth index

tensor([[0.5366, 0.7294, 0.2809, 0.9503, 0.5438, 0.6316, 0.8558, 0.9918, 0.1428,
         0.8165, 0.8692, 0.3858, 0.9178, 0.7643, 0.8865, 0.2264, 0.4073, 0.8062,
         0.5943, 0.4914]])


tensor([0.5366, 0.7294, 0.2809, 0.9503, 0.5438, 0.6316, 0.8558, 0.9918, 0.1428,
        0.8165, 0.8692, 0.3858, 0.9178, 0.7643, 0.8865, 0.2264, 0.4073, 0.8062,
        0.5943, 0.4914])

## NumPy and PyTorch

In [48]:
import numpy as np


In [49]:
a = torch.tensor([1,2,3])
a # this is a tensor

tensor([1, 2, 3])

In [50]:
b = a.numpy() # converting to numpy
b

array([1, 2, 3])

In [51]:
c = np.array([1,2,3])
c # making a numpy array

array([1, 2, 3])

In [52]:
# converting it to tensor

torch.from_numpy(c)

tensor([1, 2, 3])